# Generated by Django 3.1.4 on 2020-12-30 07:30

from django.db import migrations, models
import django.db.models.deletion
import orders.models.order
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=orders.models.order.set_order_number, max_length=100, verbose_name='Order number')),
                ('order_status', models.CharField(choices=[('1', 'Order is begin registered'), ('2', 'Delivered to the sales unit'), ('3', 'Loading'), ('4', 'Sending'), ('5', 'Cleared')], default='1', max_length=1, verbose_name='Order status')),
                ('total_cost', models.PositiveIntegerField(null=True, verbose_name='Total cost')),
                ('total_off', models.PositiveIntegerField(verbose_name='Off')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, region=None, verbose_name='Phone number')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('off', models.PositiveIntegerField(verbose_name='Off')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
